### ISSUE TITLE
Tensorflow Has No Module 'inv'

### ISSUE THREAD

**Issue by sealneaward** [RobRomijnders/RNN_basketball#1]
Was running through the model and found a compilation error.

```
Traceback (most recent call last):
  File "main.py", line 85, in <module>
    model = Model(config)
  File "/home/neil/projects/RNN_basketball/model.py", line 101, in __init__
    normalize_theta = tf.inv(tf.reduce_sum(self.theta, 1, keep_dims=True))
AttributeError: 'module' object has no attribute 'inv'
```

It looks like inv was deprecated.

**Comment by rajshah4** [comment]
I think its changed to tf.reciprocal now, we will need to update the code
